config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  get 'signup' => 'users#new'
  post 'signup' =>  'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'

  resources :posts do
    resources :votes, :only => [:create]
    resources :comments, :only => [:create] do
      resources :comments, :only => [:create]
      resources :votes, :only => [:create]
    end
  end

  resources :passwords, except: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments
  has_many :votes, as: :votable
  validates :title,
    presence: true,
    length: {minimum: 10, maximum: 100}

  validates :link,
  presence: true,
  format: {with: URI.regexp}

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :comments
  # Posts created by the user
  has_many :posts
  # Votes about this user (via votable)
  has_many :votes, as: :votable
  # Votes cast by the user (via user_id foreign key)
  has_many :ratings, class_name: 'Vote'

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false}

  validates_presence_of :password, on: :create

  def self.authenticate email,password
    User.find_by_email(email).try(:authenticate, password)
  end

  def set_password_reset
    self.code = SecureRandom.urlsafe_base64
    self.expires_at = 4.hours.from_now
    self.save
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated?
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    current_user.comments << @comment

    if @comment.save
      flash[:success] = "Comment Created!"
      redirect_to @post
    else
      flash[:danger] = "Comment not created!"
      redirect_to @post
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user
      user.set_password_reset
      UserMailer.password_reset(user).deliver
    end

    flash["success"] = "Password Was Reset"
    redirect_to login_path
  end

  def edit
    @user = User.find_by_code(params[:id])
  end

  def update
    user = User.find_by_code(params[:id])

    if user # && Time.now < user.expires_at
      user.password = params[:user][:password]
      user.code = nil
      user.expires_at = nil
      user.save
    end

    flash["success"] = "Password Was Reset"
    redirect_to login_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all
    @vote = Vote.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      flash[:success] = "Link Posted!"
      redirect_to posts_path
    else
      flash[:danger] = "Unsuccessful: Make sure the title contains at least 10 characters and that you have a valid url."
      redirect_to posts_path
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.update(params[:id], post_params)
    redirect_to posts_path
  end

  def destroy
    @post = current_user.posts.destroy(params[:id])
    redirect_to posts_path
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comment = Comment.new
    @vote = Vote.new
  end

  private

  def post_params
    params.require(:post).permit(:title,:link,:user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.authenticate(params[:user][:email], params[:user][:password])

    if @user
      session[:user_id] = @user.id
      flash[:success] = "Login Successful!"
      redirect_to posts_path
    else
      flash[:danger] = "Credentials Invalid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "User has logged out"
    redirect_to login_path
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_action :is_authenticated?, only: [:home]

  def index
    @post = Post.all
    @vote = Vote.new
    respond_to do |format|
      format.json{ render json:@posts }
      format.xml{ render xml:@posts }
      format.html
    end
  end

  def about
  end

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:name)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create

    if params.key?(:comment_id)
      thing = Comment.find_by_id(params[:comment_id])
      @post = Post.find(params[:post_id])
      return_page = @post
    elsif params.key?(:post_id)
      thing = Post.find_by_id(params[:post_id])
      return_page = :posts
    elsif params.key?(:user_id)
      thing = User.find_by_id(params[:user_id])
      return_page = :users
    else
      return render plain: "invalid input. Stop it!"
    end

    my_vote = thing.votes.find_by_user_id(current_user)

    if my_vote.nil?
      current_user.ratings << thing.votes.create(vote_params)
    else
      if(params[:vote][:value] != my_vote.value)
        my_vote.value=params[:vote][:value]
        my_vote.save
      else
        flash[:danger] = "You already voted on that!"
      end
    end
      redirect_to return_page

  end

  private

  def vote_params
    params.require(:vote).permit(:value)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %> col-md-8 col-md-offset-2">
    <%= v %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">UGen</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Post New Link", new_post_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Register", signup_path %></li>
            <li><a href="/posts/show">Profile</a></li>
            <li><%= link_to "Log In", login_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<body>
<%= render "layouts/flash" %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post:</h1>

<%= bootstrap_form_for @post do |f| %>
<%= f.text_field :title, :placeholder => "Title" %>
<%= f.text_field :link, :placeholder => "Link" %>
<%= f.primary %>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="link-title">UGen.news</h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Vote</th>
          <th>Rating</th>
          <th>Comments</th>
          <th>Title</th>
          <th>Member</th>
        </tr>
      </thead>
      <tbody>

        <% @post.each do |p| %>
        <tr>
          <td>
            <%= bootstrap_form_for [p,@vote] do |f| %>
            <%= f.hidden_field :value, value: "1" %>
            <%= f.button "", class: "btn btn-info btn-xs glyphicon glyphicon-thumbs-up" %>
            <% end %>
            <%= bootstrap_form_for [p,@vote] do |f| %>
            <%= f.hidden_field :value, value: "-1" %>
            <%= f.button "", class: "btn btn-danger btn-xs glyphicon glyphicon-thumbs-down" %>
            <% end %>
          </td>
          <td>
            <div class="rating"><%= p.votes.reduce(0){|sum,v| sum.to_i+v.value.to_i} %></div>
          </td>
          <td>
            <%= p.comments.length %>
          </td>
          <td>
            <%= link_to p.title, p %>
          </td>
          <td>
            <%= p.user.email %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<h1>New post:</h1>

<%= bootstrap_form_for @post do |f| %>
<%= f.text_field :title, :placeholder => "Title" %>
<%= f.text_field :link, :placeholder => "Link" %>
<%= f.primary %>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1><%= link_to @post.title, @post.link %></h1>
   <div class="comment-table">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Vote</th>
          <th>User</th>
          <th>Comment</th>
        </tr>
      </thead>
      <tbody>
      <% @post.comments.each do |c| %>
        <tr>
          <td class="text-center">
            <%= bootstrap_form_for [@post, c, @vote] do |f| %>
            <%= f.hidden_field :value, value: "1" %>
            <%= f.button "", class: "btn btn-info btn-xs glyphicon glyphicon-thumbs-up" %>
            <% end %>
            <div class="rating"><%= c.votes.reduce(0){|sum,v| sum.to_i+v.value.to_i} %></div>
            <%= bootstrap_form_for [@post, c, @vote] do |f| %>
            <%= f.hidden_field :value, value: "-1" %>
            <%= f.button "", class: "btn btn-danger btn-xs glyphicon glyphicon-thumbs-down" %>
            <% end %>
          </td>
          <td><%= c.user.email %></td>
          <td><%= c.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
   </div>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= bootstrap_form_for [@post,@comment] do |f| %>
        <%= f.text_area :body, :placeholder => "Leave a comment..." %>
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/site/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="link-title">UGen.news</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Vote</th>
          <th>Title</th>
          <th><i class="glyphicon glyphicon-user"></i>  User</th>
        </tr>
      </thead>
      <tbody>

        <% @post.each do |p| %>
        <tr>
          <td class="text-center">
            <%= bootstrap_form_for [p,@vote] do |f| %>
            <%= f.hidden_field :value, value: "1" %>
            <%= f.button "", class: "btn btn-primary btn-xs glyphicon glyphicon-chevron-up" %>
            <% end %>
          <div class="rating"><%= p.votes.reduce(0){|sum,v| sum.to_i+v.value.to_i} %></div>
            <%= bootstrap_form_for [p,@vote] do |f| %>
            <%= f.hidden_field :value, value: "-1" %>
            <%= f.button "", class: "btn btn-danger btn-xs glyphicon glyphicon-chevron-down" %>
            <% end %>
          </td>
          <td>
            <div><%= link_to p.title, p.link %></div>
            <br>
            <div class="comment-count pull-right"><%= link_to " #{p.comments.length}", p, :class => "btn btn-success btn-xs glyphicon glyphicon-comment" %></div>
          </td>
          <td>
            <%= p.user.email %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/users/new.html.erb
<h1>Register for an account</h1>

<%= bootstrap_form_for :user do |f| %>
<%= f.text_field :email, :placeholder => "Email" %>
<%= f.text_field :name, :placeholder => "First Name" %>
<%= f.password_field :password, :placeholder => "Password" %>
<%= f.primary %>
<% end %>